project:
  type: website
  output-dir: website
  preview:
    port: 7777
    browser: true
    watch-inputs: true
  render: 
    - index.qmd
website:
  title: ""
  favicon: img/favicon.ico
  search: false
  navbar: false
format:
  html:
    theme: style/style.scss
    grid:
      # sidebar-width: 300px
      body-width: 900px
      margin-width: 380px
      gutter-width: 8px 
    toc: false
    page-layout: article
    fontsize: 15px
    anchor-sections: false