project:
  type: website
  output-dir: website
  preview:
    port: 1111
    browser: true
    watch-inputs: true
  render: 
    - index.qmd
website:
  title: "Marie Neurath"
  favicon: img/favicon.ico
  search: false
  navbar: false
format:
  html:
    theme: [style/styles.scss]
    toc: false
    page-layout: article
    fontsize: 16px