---
title: "DIE EMISSIONEN DER WENIGEN <br> DIE LASTEN DER VIELEN"
execute:
  eval: true
  echo: false
  output: true
  warning: false
  error: true
  include: true
  cache: false
---

{{< include src/00_config.qmd >}}
{{< include src/00_libs.qmd >}}
{{< include src/00_utils.qmd >}}
{{< include src/01_isotype.qmd >}}
{{< include src/02_chimneytype.qmd >}}
{{< include src/03_deciletype.qmd >}}

```{ojs}
//| echo: false
//| output: false
arrowRightBase = "M35 138C160.529 259.062 328.006 192.715 361 184.482 M343.69 257C355.23 209.711 361 185.319 361 183.823C361 181.579 327.488 165.87 312 142"
arrowLeftBase = "M365 138C239.471 259.062 71.994 192.715 39 184.482 M56.31 257C44.77 209.711 39 185.319 39 183.823C39 181.579 72.512 165.87 88 142"

arrowRight = rotatePath(arrowRightBase, 125)  // pointing up-right
arrowLeftHigh = rotatePath(arrowLeftBase, -125)  // pointing up-left (symmetric to right)
arrowLeft = rotatePath(arrowLeftBase, -125)  // pointing up-left (symmetric to right)
arrowLeftMedium = rotatePath(arrowLeftBase, -125)  // pointing up-left (symmetric to right)
```

```{ojs}
//| echo: false
//| output: false
baseData = [
  { decile: 1, group: "Arme", position: 0, label: "Arme", arrow: "right", xArrow: -1, yArrow: -28 },
  { decile: 2, group: "na", position: 1 },
  { decile: 3, group: "Untere Mittelschicht", position: 2, label: ["Untere", "Mittelschicht"], arrow: "right", xArrow: 1, yArrow: -28 },
  { decile: 4, group: "na", position: 3 },
  { decile: 5, group: "Mittelschicht", position: 4, label: "Mittelschicht", arrow: "right", xArrow: 3, yArrow: -28 },
  { decile: 6, group: "na", position: 5 },
  { decile: 7, group: "Obere Mittelschicht", position: 6, label: ["Obere", "Mittelschicht"], arrow: "right", xArrow: 5, yArrow: -28 },
  { decile: 8, group: "Andere", position: 7 },
  { decile: 9, group: "Andere", position: 8 },
  { decile: 10, group: "Reiche", position: 9, label: "Reiche", arrow: "leftHigh", xArrow: 9.7, yArrow: -28 }
]

addHighlight = d => ({ ...d, isHighlighted: d.group === selectedQuantile || d.group === "Reiche" })

labelData = baseData.filter(d => d.label).map(addHighlight)
decileData = baseData.map(addHighlight)
```

```{ojs}
//| echo: false
html`<svg width="0" height="0" style="position: absolute;">
  <defs>
    <pattern id="hatch_right" patternUnits="userSpaceOnUse" width="3" height="3">
      <path d="M0,3 L3,0" stroke="#333333" stroke-width="0.6" fill="none" />
    </pattern>
    <pattern id="hatch_left" patternUnits="userSpaceOnUse" width="3" height="3">
      <path d="M0,0 L3,3" stroke="#333333" stroke-width="0.6" fill="none" />
    </pattern>
  </defs>
</svg>`
```

```{ojs}
//| echo: false
makeDeciletype({
  decileData: decileData,
  labelData: labelData,
  arrowLeftHigh: arrowLeftHigh,
  arrowLeft: arrowLeft,
  arrowLeftMedium: arrowLeftMedium,
  arrowRight: arrowRight,
  vizWidth: 600,
  vizHeight: 30
})
.render({ renderer: "svg" })
```

```{ojs}
//| echo: false
//| output: false
data = FileAttachment("data/data.csv").csv({ typed: true })

filteredData = data
  .filter(d => d.name != "Emissionen Gesamt")
  .filter(d => d.Quantile === selectedQuantile || d.Quantile === "Reiche")
```

<div class = "grayContainer">

```{ojs}
//| echo: false
width >= 860 ?
  html`<div style="display: flex; justify-content: center; align-items: center; gap: 30px; font-family: Jost; font-size: 15px; padding-top: 16px; padding-bottom: 16px;">
    <div style="display: flex; align-items: flex-end; gap: 4px;">
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path2}" fill="${colors_new[4]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <span style="font-weight: 400;">≈ 500 kg CO₂ pro Person und Jahr</span>
    </div>
    <div style="display: flex; align-items: flex-end; gap: 4px;">
      <svg width="20" height="34" viewBox="0 0 16 24" style="vertical-align: middle; margin: 0;">
        <path d="${path2_half}" fill="${colors_new[4]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <span style="font-weight: 400;">≈ 250 kg CO₂ pro Person und Jahr</span>
    </div>
  </div>`
  :
  htl.html`<div></div>`
```

```{ojs}
//| echo: false
{
  const viz = await makeIsotype({
    inputData: filteredData,
    spacing: -50,
    height: 200,
    size: 8,
    divisor: 500,
    unit: "t CO₂",
    colorRange: colors_new,
    showHeader: width >= 860 ? false : true
  })
    .config(config)
    .render({ renderer: "svg" });

  return html`<div style="display: flex; justify-content: center; background-color: "transparent"; padding: 10px;">
    ${viz}
  </div>`;
}
```

<!-- 
```{ojs}
//| echo: false
width >= 860 ?
  html`<div style="display: flex; justify-content: center; align-items: center; gap: 30px; font-family: Jost; font-size: 15px; padding-top: 20px; padding-bottom: 20px;">
    <div style="display: flex; align-items: flex-end; gap: 4px;">
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path1}" fill="${colors_new[2]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path2}" fill="${colors_new[4]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path4}" fill="${colors_new[3]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path5}" fill="${colors_new[1]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="32" height="32" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path6}" fill="${colors_new[0]}" stroke="black" stroke-width="0.722" opacity="0.811"/>
      </svg>
      <span style="font-weight: 400;">≈ 0,5 t CO₂ pro Jahr</span>
    </div>
    <div style="display: flex; align-items: flex-end; gap: 0px;">
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path1_half}" fill="${colors_new[2]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path2_half}" fill="${colors_new[4]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path4_half}" fill="${colors_new[3]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="34" height="34" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path5_half}" fill="${colors_new[1]}" stroke="black" stroke-width="0.649" opacity="0.811"/>
      </svg>
      <svg width="32" height="32" viewBox="0 0 24 24" style="vertical-align: middle; margin: 0;">
        <path d="${path6_half}" fill="${colors_new[0]}" stroke="black" stroke-width="0.722" opacity="0.811"/>
      </svg>
      <span style="font-weight: 400;">≈ 0,25 t CO₂ pro Jahr</span>
    </div>
  </div>`
  :
  htl.html`<div></div>`
```
 -->

```{ojs}
//| echo: false
//| output: false
filteredEmissionen = data
  .filter(d => d.name == "Emissionen Gesamt")
  .filter(d => d.Quantile === selectedQuantile || d.Quantile === "Reiche")
```

---

```{ojs}
//| echo: false
{
  if (width >= 860) {
    const viz = await makeChimneytype({
      inputData: filteredEmissionen,
      shapeDomain: ["Emissionen Gesamt"],
      shapeRange: [path7],
      shapeRangeHalf: [path7_half],
      colorRange: ["#474A51"],
      height: 100,
      size: 8,
      unit: "t CO₂",
      divisor: 500,
      showHeader: false,
      iconsPerRow: 10
    })
      .config(config)
      .render({ renderer: "svg" });

    return html`<div style="display: flex; justify-content: center; background-color: "transparent"; padding: 10px;">
      ${viz}
    </div>`;
  } else {
    return htl.html`<div></div>`;
  }
}
```

</div>

<div class="comparison-container">
  <span class="comparison-left">Vergleich</span>
```{ojs}
//| echo: false
viewof selectedQuantile = Inputs.select(
  ["Arme", "Untere Mittelschicht", "Mittelschicht", "Obere Mittelschicht"],
  { label: "Vergleich ", value: "Arme" }
)
```
<span class="comparison-right">mit Reiche</span>
</div>


### HINTERGRUND

Wirksamer Klimaschutz muss soziale Gerechtigkeit mitdenken. Neuen [**Daten**](https://doi.org/10.1111/jiec.70074){target="_blank"} zufolge verursachen die nach Pro-Kopf-Haushaltseinkommen **reichsten 10%** der Bevölkerung in Österreich pro Kopf **mehr als dreimal** so hohe CO₂-Emissionen wie die **ärmsten 10%**.[^1] Diese Ungleichheit ist besonders bei [**Mobilität**]{style="color: #3E6F8E;"}, [**Wohnen**]{style="color: #D62300;"} und [**Dienstleistungen**]{style="color: #198737;"} ausgeprägt. Diese Emissionen führen zu hohen gesellschaftlichen Kosten infolge steigender Temperaturen, etwa durch extreme Wetterereignisse, Produktivitätsverluste und zusätzlichen gesundheitlichen Belastungen. Diese Kosten werden von allen getragen, unabhängig davon, ob eine einzelne Person mehr oder weniger Emissionen verursacht. Um die Auswirkungen zumindest zu begrenzen, dürfte 2025 eine Person nur etwa 3 Tonnen an CO₂-Äquivalenten emittieren[^2]. Ein Wert den alle Einkommensdezile in Österreich überschreiten — allen voran Personen mit höherem Einkommen.

[^1]: Diese Schätzungen beziehen sich auf das Jahr 2020 und basieren auf einer Datenkombination aus multiregionalen Input-Output-Tabellen, Umfragedaten der österreichischen Konsumerhebung, und Daten aus der österreichische Luftschadstoff- und Treibhausgas-Inventur (THGI) (Dorninger et al. 2025). Die Daten inkludieren andere Treibhausgase und beziehen sich auf CO₂-Äquivalente. 

[^2]: Schätzwert für 2025 berechnet anhand des österreichischen Anteils am global maximalen Emissionswert zur Erreichung des +1,5°C Ziels und einer konstanten prozentualen Abnahme der Emissionen ab 2022. Siehe: [Climate Change Center Austria (CCCA) 2022](https://ccca.ac.at/fileadmin/00_DokumenteHauptmenue/02_Klimawissen/Papiere/THG-Budget_Hintergrundpapier_CCCA.pdf){target="_blank"}: 1,5° C: Wieviel Treibhausgase dürfen wir noch emittieren? Hintergrundpapier zu globalen und nationalen Treibhausgasbudgets.

Die **Wiener Methode der Bildstatistik** (Isotype) macht diese abstrakte Verteilungsfrage unmittelbar erfassbar: Jedes Symbol steht für eine konkrete Menge CO₂. Was **Marie** und **Otto Neurath** in den 1920er-Jahren für wirtschaftliche und soziale Zusammenhänge entwickelten, zeigt auf einen Blick, wie drastisch die Emissionen zwischen Arm und Reich auseinanderklaffen.

### AUTOREN

[**Fabian Kalleitner**](https://www.ls4.soziologie.uni-muenchen.de/personen/wissenschaftlich_mitarbeiter/fabian_kalleitner/index.html){target="_blank"} — [**Lukas Schmoigl**](https://www.wifo.ac.at/person/lukas-schmoigl/){target="_blank"}

### DATEN

Dorninger, Christian, Simone Gingrich, Willi Haas, Alina Brad, Etienne Schneider, and Dominik Wiedenhofer. 2025. "Slow and Unequal Reduction in Austrian Household GHG Footprints Between 2000 and 2020." *Journal of Industrial Ecology* 29 (5): 1651–65. [**Link**](https://doi.org/10.1111/jiec.70074){target="_blank"}.
